apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: spring-app
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # "postgres" in base64
  POSTGRES_PASSWORD: bWFyaWph  # "marija" in base64
